### PR TITLE
Test atomicity of operations and actions

### LINKED ISSUE #106: Confirm atomic wallet calls, not whole transaction
Audit issue 4. "A single operation causes all other operations in an execution cycle to fail"
"Should one of these calls fail, the whole transaction reverts"

Show this is not the case with a unit test.

### PR DESCRIPTION
**Pull request by voltrevo**
## What is this PR doing?

Adds tests:
- should allow other operations when one fails
- should prevent other actions within an operation when one fails

## How can these changes be manually tested?

Run the new tests.

## Does this PR resolve or contribute to any issues?

Resolves #106.

## Checklist
- [x] I have manually tested these changes
- [x] Post a link to the PR in the group chat

## Guidelines
- If your PR is not ready, mark it as a draft
- The `resolve conversation` button is for reviewers, not authors
  - (But add a 'done' comment or similar)

### CODE REVIEW

File: contracts/shared/helpers/TokenHelper.ts [hunk 1]
```diff
@@ -56,7 +57,7 @@ export default class TokenHelper {
   async walletTokenSetup(): Promise<BlsWalletWrapper[]> {
     const wallets = await this.fx.createBLSWallets();
 
-    this.testToken = await TokenHelper.deployTestToken();
+    this.testToken = (await TokenHelper.deployTestToken()) as IERC20;
```
Comment (jacque006) [inline contracts/shared/helpers/TokenHelper.ts:60]: You could modify [TokenHelper.deployTestToken](https://github.com/jzaki/bls-wallet/blob/main/contracts/shared/helpers/TokenHelper.ts#L22-L29) to use the Typechain factory and contract type instead of doing the type cast here.

**Review by jacque006 — APPROVED** [review]
