### PR TITLE
Fix docker build

### LINKED ISSUE #80: Fix aggregator docker build to work with network config
Network config typically points to a json file outside the aggregator subproject. Therefore it won't be included in the docker build and won't work. Fix it.

### PR DESCRIPTION
**Pull request by voltrevo**
## What is this PR doing?

The docker build was broken because our .env now generally points to a networkConfig outside the aggregator subproject, and therefore isn't available inside the docker image.

This fixes that by copying the networkConfig to the top-level and updating this value in the built .env file.

Also refactors `build.ts` into separate functions. You might prefer to go commit-by-commit to inspect the changes.

## How can these changes be manually tested?

1. Run the build `./programs/build.ts --sudo-docker`
2. Run the image and check that it starts up normally `sudo docker run --rm -it --net=host <insert image name from build log>`

## Does this PR resolve or contribute to any issues?

Resolves #80

## Checklist
- [x] I have manually tested these changes
- [x] Post a link to the PR in the group chat

## Guidelines
- If your PR is not ready, mark it as a draft
- The `resolve conversation` button is for reviewers, not authors
  - (But add a 'done' comment or similar)

### CODE REVIEW

File: aggregator/programs/build.ts [hunk 1]
```diff
@@ -5,103 +5,164 @@ import { dirname, parseArgs } from "../deps.ts";
...
-      "git",
-      "ls-files",
-      "--others",
-      "--exclude-standard",
-    ),
-  ];
+  await shell.run(
+    "gzip",
+    `${repoDir}/build/${dockerImageName}.tar`,
+  );
```
Comment (jacque006) [inline aggregator/programs/build.ts:167]: Can consider pushing this to a container image registry in the future such as Docker Hub. https://github.com/thehubbleproject/hubble-contracts/blob/master/.github/workflows/docker.yml

File: aggregator/programs/build.ts [hunk 2]
```diff
@@ -5,103 +5,164 @@ import { dirname, parseArgs } from "../deps.ts";
...
 
-  console.log("Processing", f);
-  await Deno.mkdir(dirname(`${buildDir}/ts/${f}`), { recursive: true });
-  await Deno.copyFile(f, `${buildDir}/ts/${f}`);
+  if (networkConfigPaths !== nil) {
+    await Deno.copyFile(
+      networkConfigPaths.repo,
+      `${buildDir}/${networkConfigPaths.build}`,
+    );
+  }
```
Comment (jacque006) [inline aggregator/programs/build.ts:110]: Generally when running containerized services, the container image does not have configuration included in the image (asides from safe/needed defaults) and instead the user provides that via [a variety of options](https://docs.docker.com/engine/reference/run/#overriding-dockerfile-image-defaults), most common being command overrides, env vars, and file/volume mounts. `geth` for example uses command overrides and volume mounts for loading and persisting data https://github.com/jzaki/bls-wallet/blob/main/docker-compose.yml#L26-L34 . We can consider updating how we want to do that in the future.

**Review by jacque006 — APPROVED** [review]
