### PR TITLE
Bundle error logging

### LINKED ISSUE #301: Add better failure messaging for bundles
As an aggregator operator (and maybe consumer), I would like to know why a bundle has not been submitted so I can more easily troubleshoot issues with my aggregator configuration or bundles I submit.

### Possible solution(s)
- Log out when a bundle fails to be included in the next submission and why it was not included.
- Return an error/failure status and the reason for the error/failure when querying `/bundleReceipt/:hash`.

### PR DESCRIPTION
**Pull request by blakecduncan**
https://loom.com/share/2a2039a17af04e23838561a08b0c6aaf

## What is this PR doing?
- Adding a submit error column to the DB
- Updating the bundle receipt API call to return a 202 if the bundle exists in the DB
- New response object for bundle receipt API call (note: this will break demos.  It's a simple fix but I want to make sure it is okay with everyone)

Additional work
- We would need to update examples and the extension because right now, they expect the `/bundleReceipt` API call to return a 404 when a bundle is pending.

Future improvements
- Add a status column to the bundles table so that we don't delete bundles when the are successful or fail (we are currently storing the successful bundles in memory)

## How can these changes be manually tested?
You can run the zeroAddressError script to trigger a bundle error and log out a message

## Does this PR resolve or contribute to any issues?
Resolves https://github.com/web3well/bls-wallet/issues/301

## Checklist
- [x] I have manually tested these changes
- [x] Post a link to the PR in the group chat

## Guidelines
- If your PR is not ready, mark it as a draft
- The `resolve conversation` button is for reviewers, not authors
  - (But add a 'done' comment or similar)

### CODE REVIEW

File: aggregator/manualTests/zeroAddressError.ts [hunk 1]
```diff
@@ -0,0 +1,50 @@
+#!/usr/bin/env -S deno run --allow-net --allow-env --allow-read --allow-write --unstable
```
Comment (blakecduncan) [inline aggregator/manualTests/zeroAddressError.ts:1]: This is just a script to trigger an error in a bundle for testing

File: aggregator/src/app/AggregationStrategy.ts [hunk 2]
```diff
@@ -235,11 +235,16 @@ export default class AggregationStrategy {
       let success: boolean;
 
       if (bundleResult.success) {
-        const [operationResults] = bundleResult.returnValue;
+        const [operationStatuses, results] = bundleResult.returnValue;
```
Comment (blakecduncan) [inline aggregator/src/app/AggregationStrategy.ts]: When there is a failure this results variable has some data in it.  I haven't been able to decode that value though.  I get an out of bounds error everytime I try.  If anyone knows if I can decode that let me know.  Or if it is even worth trying to decode the value.

See comment in the code below for an example of a value that is returned

File: aggregator/src/app/EthereumService.ts [hunk 3]
```diff
@@ -302,6 +302,19 @@ export default class EthereumService {
...
 
+      try {
+        const result = attemptResult.value.events[0].args.results[0]; // For errors this is "Error(string)"
+        const errorArgBytesString = `0x${result.substring(10)}`; // remove methodId (4bytes after 0x)
+        const errorString = ethers.utils.defaultAbiCoder.decode(
+          ["string"],
+          errorArgBytesString,
+        )[0]; // decoded bytes is a string of the action index that errored.
+
+        console.error(errorString)
```
Comment (blakecduncan) [inline aggregator/src/app/EthereumService.ts]: I'm not sure if there's anything else we can do here other than just log out the message?  If you have thoughts let me know

File: aggregator/src/app/AggregationStrategy.ts [hunk 4]
```diff
@@ -235,11 +235,16 @@ export default class AggregationStrategy {
...
+
+        // TODO: is it possible to decode this?
+        // Here is an example when I try to send more ETH than an account has:results =
+        // results = [ "0x4e487b710000000000000000000000000000000000000000000000000000000000000011" ]
```
Comment (jacque006) [inline aggregator/src/app/AggregationStrategy.ts]: ~Would the work in https://github.com/web3well/bls-wallet/pull/366 help with this?~ See https://github.com/web3well/bls-wallet/pull/377/files#r1019631375 (comment above ^)

File: aggregator/src/app/AggregationStrategy.ts (hunk 2 above)
Comment (jacque006) [reply aggregator/src/app/AggregationStrategy.ts]: I wouldn't worry about decoding the results for this work as we have https://github.com/web3well/bls-wallet/issues/364 to address this. Would focus on bubbling up human readable errors from submitted bundles.

File: aggregator/src/app/EthereumService.ts [hunk 5]
```diff
@@ -302,6 +302,21 @@ export default class EthereumService {
...
       const attemptResult = await attempt();
 
+      try {
+        if (attemptResult.value.events[0]?.args?.results[0]) {
+          const result = attemptResult.value.events[0].args.results[0]; // For errors this is "Error(string)"
+          const errorArgBytesString = `0x${result.substring(10)}`; // remove methodId (4bytes after 0x)
+          const errorString = ethers.utils.defaultAbiCoder.decode(
+            ["string"],
+            errorArgBytesString,
+          )[0]; // decoded bytes is a string of the action index that errored.
```
Comment (jacque006) [inline aggregator/src/app/EthereumService.ts]: If https://github.com/web3well/bls-wallet/pull/366 goes in before this, you can just use that lib method.

Comment (blakecduncan) [reply aggregator/src/app/EthereumService.ts]: Yeah that is a good call.  I'll probably do that

Comment (jacque006) [reply aggregator/src/app/EthereumService.ts]: Actually available right meow https://github.com/web3well/bls-wallet/blob/main/contracts/clients/README.md#verificationgateway

File: aggregator/src/app/AggregationStrategy.ts [hunk 6]
```diff
@@ -444,3 +461,89 @@ export default class AggregationStrategy {
     return left;
   }
 }
+
+// The below code is temporary till the functions are exposed in the client module
```
Comment (blakecduncan) [inline aggregator/src/app/AggregationStrategy.ts]: After this is merged and a new version is published, I will delete the below code and use the function from the client module

https://github.com/web3well/bls-wallet/pull/407

File: aggregator/src/app/AggregationStrategy.ts [hunk 7]
```diff
@@ -231,22 +236,34 @@ export default class AggregationStrategy {
...
+            return;
+          }
+        });
+        errorReason = error[0] !== undefined
+          ? error[0]
+          : null;
+      }
 
-      return { success, fee };
+      return { success, fee, errorReason };
```
Comment (blakecduncan) [inline aggregator/src/app/AggregationStrategy.ts:272]: Returning the error reason here so that we can link it to a failed row later when we check the index of the failed bundle

File: aggregator/src/app/BundleRouter.ts [hunk 8]
```diff
@@ -24,6 +24,16 @@ export default function BundleRouter(bundleService: BundleService) {
   router.get(
     "bundleReceipt/:hash",
     async (ctx) => {
+      // check pending
```
Comment (blakecduncan) [inline aggregator/src/app/BundleRouter.ts]: Return 202 error message if the bundle is in the DB.  Also, pass a submit error in the body

File: aggregator/src/app/AggregationStrategy.ts [hunk 9]
```diff
@@ -231,22 +236,36 @@ export default class AggregationStrategy {
...
-
-      if (bundleResult.success) {
-        const [operationResults] = bundleResult.returnValue;
-
-        // We require that at least one operation succeeds, even though
-        // processBundle doesn't revert in this case.
-        success = operationResults.some((opSuccess) => opSuccess === true);
-      } else {
-        success = false;
+      const fee = after.returnValue[0].sub(before.returnValue[0]);
```
Comment (jacque006) [inline aggregator/src/app/AggregationStrategy.ts:241]: Will this break if someone submits a bundle with 0 operations?

File: aggregator/src/app/AggregationStrategy.ts [hunk 10]
```diff
@@ -231,22 +236,36 @@ export default class AggregationStrategy {
...
+      if (!bundleResult.success) {
+        return { success: false, fee, errorReason: null };
```
Comment (jacque006) [inline aggregator/src/app/AggregationStrategy.ts]: Should the `errorReason` here be the decoded error results form the bundle operations? Or in the case of a txn revert the top level error message?

File: aggregator/src/app/AggregationStrategy.ts [hunk 11]
```diff
@@ -231,22 +236,36 @@ export default class AggregationStrategy {
...
+      if (!success) {
+        const error = results.map((result: string[]) => {
+          try {
+            if (result[0]) {
+              return decodeError(result[0]);
+            }
+            return;
+          } catch (_err) {
+            return;
+          }
```
Comment (jacque006) [inline aggregator/src/app/AggregationStrategy.ts]: Would be good to log out the error here. May even be worth adding and emitting as an `AppEvent`.

```suggestion
          } catch (err) {
            console.error(err);
            return;
          }
```

File: aggregator/src/app/AggregationStrategy.ts [hunk 12]
```diff
@@ -231,22 +236,36 @@ export default class AggregationStrategy {
...
+        });
+        errorReason = error[0] !== undefined
+          ? error[0]
+          : null;
```
Comment (jacque006) [inline aggregator/src/app/AggregationStrategy.ts]:
```suggestion
        const errorReason = error[0] ?? null;
```

File: aggregator/src/app/BundleRouter.ts [hunk 13]
```diff
@@ -24,14 +24,29 @@ export default function BundleRouter(bundleService: BundleService) {
   router.get(
     "bundleReceipt/:hash",
     async (ctx) => {
+      const pendingBundle = await bundleService.lookupBundle(ctx.params.hash!);
+      if (pendingBundle) {
+        ctx.response.status = 202;
+        ctx.response.body = {
+          status: "pending",
+          submitError: pendingBundle.submitError,
```
Comment (jacque006) [inline aggregator/src/app/BundleRouter.ts]: I believe after 5 tries the bundle will be in a permanent failed state. Is there a way to communicate that here? That may be for another issue to address.

**Review by jacque006 — COMMENTED** [review]
Would be good to have an integration test case(s) for the `HTTP 202` path that ensures the bundle lifecycle & error decoding works as expected.

File: aggregator/src/app/AggregationStrategy.ts (hunk 9 above)
Comment (blakecduncan) [reply aggregator/src/app/AggregationStrategy.ts:241]: hmm I don't think so.  This logic isn't any different than it was before.  I just moved this line up so I could have an early return case to get rid of some of the nested if statements.

File: aggregator/src/app/AggregationStrategy.ts (hunk 10 above)
Comment (blakecduncan) [reply aggregator/src/app/AggregationStrategy.ts]: Yeah, that's a good question @jacque006.  I'm really not sure what to put here for the errorReason.  Whenever `bundleResult.success` is `false` there isn't anything returned for me to decode.

File: aggregator/src/app/BundleRouter.ts (hunk 13 above)
Comment (blakecduncan) [reply aggregator/src/app/BundleRouter.ts]: Looking at the `handleFailedRow()` function in the BundleService.ts, it looks like when a bundle gets into a permanently failed state, we delete the bundle from the table.  With this setup that would mean a permanently failed bundle would return a 404 error.

I think a solution is probably to add a status column in the DB that could have 'pending', 'success', or 'failed'.  This would also fix the issue of storing successful bundles in memory.  I was torn whether to do that as part of this PR or keep it separate.

Comment (blakecduncan) [reply aggregator/src/app/BundleRouter.ts]: I created this issue as a follow up to this comment https://github.com/web3well/bls-wallet/issues/408

**Comment by blakecduncan** [comment]
> Would be good to have an integration test case(s) for the `HTTP 202` path that ensures the bundle lifecycle & error decoding works as expected.

Yeah good call, I'll write some tests for this 👍

File: aggregator/src/app/AggregationStrategy.ts (hunk 6 above)
Comment (jacque006) [reply aggregator/src/app/AggregationStrategy.ts]: @blakecduncan You can do that now https://github.com/web3well/bls-wallet/pull/407 . You can use https://github.com/web3well/bls-wallet/blob/main/docs/local_development.md#aggregator-1 as a guide, but feel free to ping me if you need help.

File: aggregator/src/app/AggregationStrategy.ts (hunk 10 above)
Comment (jacque006) [reply aggregator/src/app/AggregationStrategy.ts]: Looking through `AggregatorUtilities.sol` and the `EthereumService.ts` i think this makes a bit more sense now. Probably a larger/different discussion on how we are simulating actions.

Until then, I would put in something like `unknown` because that is the extent of what we know.

```suggestion
        return { success: false, fee, errorReason: "unknown" };
```

File: aggregator/src/app/BundleRouter.ts (hunk 13 above)
Comment (jacque006) [reply aggregator/src/app/BundleRouter.ts]: Follow up seems appropriate, thanks :+1:

**Comment by voltrevo** [comment]
> [Idk how I'm missing these lint errors](https://github.com/web3well/bls-wallet/pull/377/commits/e243212e67e45606a8b00b0cb5c97fc8af437875)

😄. How's your IDE set-up? Are the linting errors showing? Is autofix-on-save working?

File: aggregator/src/app/AggregationStrategy.ts [hunk 14]
```diff
@@ -176,6 +178,10 @@ export default class AggregationStrategy {
 
     if (firstFailureIndex !== nil) {
       const failedRow = includedRows[firstFailureIndex];
+      const errorReason = fees[firstFailureIndex].errorReason;
+      if (errorReason) {
+        failedRow.submitError = errorReason.message || '';
```
Comment (voltrevo) [inline aggregator/src/app/AggregationStrategy.ts]: Why default to an empty string instead of `undefined`/`nil`?

Also nitpick: Prefer `??` over `||`. (Unless there's a reason for `||` I'm not seeing here?)

File: aggregator/src/app/AggregationStrategy.ts [hunk 15]
```diff
@@ -207,6 +213,7 @@ export default class AggregationStrategy {
   async #measureFees(bundles: Bundle[]): Promise<{
     success: boolean;
     fee: BigNumber;
+    errorReason: OperationResultError | null;
```
Comment (voltrevo) [inline aggregator/src/app/AggregationStrategy.ts]: We don't really use `null` internally - only when something external needs it. This should probably be documented somewhere. Can you make this `nil`?

File: aggregator/src/app/AggregationStrategy.ts [hunk 16]
```diff
@@ -231,22 +238,38 @@ export default class AggregationStrategy {
...
+        const errorReason: OperationResultError = {
+          message: "Unknown error reason",
+        };
+        return { success: false, fee, errorReason };
       }
 
-      const fee = after.returnValue[0].sub(before.returnValue[0]);
+      const [operationStatuses, results] = bundleResult.returnValue;
+
+      let errorReason: OperationResultError | null = null;
```
Comment (voltrevo) [inline aggregator/src/app/AggregationStrategy.ts]: `null` -> `nil`

File: aggregator/src/app/AggregationStrategy.ts [hunk 17]
```diff
@@ -231,22 +238,38 @@ export default class AggregationStrategy {
...
+            if (result[0]) {
+              return decodeError(result[0]);
+            }
+            return;
+          } catch (err) {
+            console.error(err);
+            return;
+          }
+        });
+        errorReason = error[0] ?? null;
```
Comment (voltrevo) [inline aggregator/src/app/AggregationStrategy.ts]: Remove `?? null`

File: aggregator/src/app/BundleRouter.ts [hunk 18]
```diff
@@ -24,14 +24,29 @@ export default function BundleRouter(bundleService: BundleService) {
   router.get(
     "bundleReceipt/:hash",
     async (ctx) => {
+      const pendingBundle = await bundleService.lookupBundle(ctx.params.hash!);
+      if (pendingBundle) {
+        ctx.response.status = 202;
```
Comment (voltrevo) [inline aggregator/src/app/BundleRouter.ts]: I don't think 202 is appropriate here. It's the *bundle* that's been accepted, not the receipt. Also 'accepted' is supposed to refer to the current request, not the resource you're asking about. [More info](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202).

(Possibly 202 is appropriate for the original POST to /bundle, but I'm not actually a fan of worrying about these HTTP nuances.)

On a practical note, if we keep 404 here we can still also provide the `submitError`, and this way it wouldn't be a breaking change. Wdyt?

File: aggregator/src/app/BundleRouter.ts [hunk 19]
```diff
@@ -24,14 +24,29 @@ export default function BundleRouter(bundleService: BundleService) {
...
 
       if (receipt === nil) {
         ctx.response.status = 404;
         return;
       }
 
-      ctx.response.body = receipt;
+      ctx.response.body = {
+        status: "done",
+        submitError: null,
```
Comment (voltrevo) [inline aggregator/src/app/BundleRouter.ts]: `null`

File: aggregator/src/app/BundleService.ts [hunk 20]
```diff
@@ -184,6 +184,7 @@ export default class BundleService {
         bundle,
         eligibleAfter: await this.ethereumService.BlockNumber(),
         nextEligibilityDelay: BigNumber.from(1),
+        submitError: ''
```
Comment (voltrevo) [inline aggregator/src/app/BundleService.ts]: Why is there an empty string here? Can we just remove the field?

File: aggregator/src/app/BundleService.ts [hunk 21]
```diff
@@ -200,6 +201,11 @@ export default class BundleService {
     });
   }
 
+  async lookupBundle(hash: string) {
+    const bundleArray = await this.bundleTable.findBundle(hash);
+    return bundleArray[0] ? bundleArray[0] : nil;
```
Comment (voltrevo) [inline aggregator/src/app/BundleService.ts]: Why does `findBundle` return an array? Wouldn't `Bundle | nil` be more appropriate? That way you'd also not need to transform the result here.

File: aggregator/src/app/BundleTable.ts [hunk 22]
```diff
@@ -52,6 +54,7 @@ const tableOptions: TableOptions = {
   id: { type: DataType.Serial, constraint: Constraint.PrimaryKey },
   hash: { type: DataType.VarChar },
   bundle: { type: DataType.VarChar },
+  submitError: { type: DataType.VarChar },
```
Comment (voltrevo) [inline aggregator/src/app/BundleTable.ts]:
```suggestion
  submitError: { type: DataType.VarChar, nullable: true },
```

File: aggregator/src/app/BundleTable.ts [hunk 23]
```diff
@@ -27,6 +27,7 @@ type RawRow = {
   bundle: string;
   eligibleAfter: string;
   nextEligibilityDelay: string;
+  submitError: string;
```
Comment (voltrevo) [inline aggregator/src/app/BundleTable.ts]:
```suggestion
  submitError: string | null;
```

File: aggregator/src/app/BundleTable.ts [hunk 24]
```diff
@@ -35,6 +36,7 @@ type Row = {
   bundle: Bundle;
   eligibleAfter: BigNumber;
   nextEligibilityDelay: BigNumber;
+  submitError: string;
```
Comment (voltrevo) [inline aggregator/src/app/BundleTable.ts]:
```suggestion
  submitError?: string;
```

Note that `RawRow` reflects what we get from the database, and therefore needs to use `null` (I think). This means adding the appropriate translation in `toRawRow`, `fromRawRow` (which TypeScript will point out).

File: aggregator/test/AggregationStrategy.test.ts [hunk 25]
```diff
@@ -1,6 +1,6 @@
 import AggregationStrategy from "../src/app/AggregationStrategy.ts";
 import { BundleRow } from "../src/app/BundleTable.ts";
-import { assertEquals, BigNumber } from "./deps.ts";
+import {assertEquals, BigNumber, ethers} from "./deps.ts";
```
Comment (voltrevo) [inline aggregator/test/AggregationStrategy.test.ts]: Nitpick: Formatting. (Do you have autofix on save enabled?)

File: aggregator/test/AggregationStrategy.test.ts [hunk 26]
```diff
@@ -98,6 +98,7 @@ Fixture.test("includes bundle in aggregation when estimated fee is provided", as
   const bundleRow: BundleRow = {
     id: 0,
     hash: "0x0",
+    submitError: "",
```
Comment (voltrevo) [inline aggregator/test/AggregationStrategy.test.ts]: (See previous comment about use of empty string)

File: aggregator/test/AggregationStrategy.test.ts [hunk 27]
```diff
@@ -111,3 +112,61 @@ Fixture.test("includes bundle in aggregation when estimated fee is provided", as
...
+          ],
+        ),
+      }
+    ],
+  });
+
+  const bundleRow: BundleRow = {
+    id: 0,
+    hash: "0x0",
+    submitError: "",
```
Comment (voltrevo) [inline aggregator/test/AggregationStrategy.test.ts]: Empty string

File: aggregator/test/BundleTable.test.ts [hunk 28]
```diff
@@ -49,6 +49,7 @@ const sampleRows: BundleRow[] = [
       ],
       signature: ["0x00", "0x00"],
     },
+    submitError: "",
```
Comment (voltrevo) [inline aggregator/test/BundleTable.test.ts]: Empty string

File: contracts/clients/src/Aggregator.ts [hunk 29]
```diff
@@ -34,9 +34,17 @@ export type EstimateFeeResponse = {
...
+  transactionHash: string;
+  bundleHash: string;
   blockHash: string;
-  blockNumber: string;
+  blockNumber: number;
+};
+
+export type BundleReceiptResponse = {
+  status: string;
+  submitError: string | null;
```
Comment (voltrevo) [inline contracts/clients/src/Aggregator.ts]: null

File: contracts/clients/src/Aggregator.ts [hunk 30]
```diff
@@ -34,9 +34,17 @@ export type EstimateFeeResponse = {
...
+  receipt: BundleReceipt | null;
```
Comment (voltrevo) [inline contracts/clients/src/Aggregator.ts]: null

File: extension/source/background/AggregatorController.ts [hunk 31]
```diff
@@ -126,21 +123,10 @@ export default class AggregatorController {
...
-            transactionHash: io.string,
-            blockHash: io.string,
-            blockNumber: io.number,
-          }),
-        ),
-      );
+      const bundleReceiptResponse = await aggregator.lookupReceipt(hash);
+      // If receipt doesn't exist, set to undefined to be consistent with
+      // the return type
+      const bundleReceipt = bundleReceiptResponse?.receipt || undefined;
```
Comment (voltrevo) [inline extension/source/background/AggregatorController.ts]: `|| undefined` is unnecessary (`obj?.field` produces `undefined` when field is not there, even when `obj` is `null`).

Also prefer `??` over `||`.

**Review by voltrevo — CHANGES_REQUESTED** [review]

File: aggregator/src/app/AggregationStrategy.ts (hunk 14 above)
Comment (blakecduncan) [reply aggregator/src/app/AggregationStrategy.ts]: @voltrevo Yeah that makes sense I'll switch it.  I was doing this because I didn't make the column nullable in the DB, so it was setting it by default to an empty string.  I updated that per your comment below and was able to make this more consistent with the undefined/nil

File: extension/source/background/AggregatorController.ts (hunk 31 above)
Comment (blakecduncan) [reply extension/source/background/AggregatorController.ts]: Yeah I was getting a typescript error the `BundleReceipt | undefined` does not equal `BundleReceipt | undefined | null`.  I think with the changes you recommended above I can fix this.

File: aggregator/src/app/BundleRouter.ts (hunk 18 above)
Comment (blakecduncan) [reply aggregator/src/app/BundleRouter.ts]: Yeah, I get what you're saying.  I do like the idea of not doing a breaking change, as there are a good amount of things that have to be updated at this point.

However, I think the `/bundleReceipt` API call is often used as a status check for a bundle.  So my question would be, what should we expect to be returned from this API call?  With the approach you recommended, we would keep a 200 status as is (i.e. returns the bundle receipt) and pass the submit error in a 404 response body.  That would be fine by me - I think the only thing we aren't communicating explicitly is the bundle status. For example, we could communicate a pending or a failed state (ex: even if it failed once, we may still retry it).  Maybe we don't care about that though or it should be a different API endpoint.

@voltrevo What do you think?  I'd be happy to hop on a call tomorrow when I get online if you are still around.  Also, @jacque006  not sure if you have any thoughts?

Comment (voltrevo) [reply aggregator/src/app/BundleRouter.ts]: I'm not sure we're on the same page here. Definitely sounds like a call is in order.

> With the approach you recommended, we would keep a 200 status as is (i.e. returns the bundle receipt) and pass the submit error in a 404 response body.

Did you mean to say 'keep a 200 status'? It seems wrong, and also contradicts the second half of this sentence. At least my reading of it.

To rephrase my suggestion, I think if the bundle is pending, then `/bundleReceipt` should 404, since there isn't a bundle receipt, but we can also put the submitError in the body of this response. Meaning: "No, there's no receipt (404), and here's why (submitError)".

File: aggregator/src/app/BundleTable.ts [hunk 32]
```diff
@@ -54,20 +55,21 @@ const tableOptions: TableOptions = {
...
-  submitError: { type: DataType.VarChar },
+  submitError: { type: DataType.VarChar, nullable: true },
   eligibleAfter: { type: DataType.VarChar },
   nextEligibilityDelay: { type: DataType.VarChar },
 };
 
 function fromRawRow(rawRow: RawRow): Row {
   const parseResult = parseBundleDto(JSON.parse(rawRow.bundle));
-
+  console.log('blake..', parseResult);
```
Comment (voltrevo) [inline aggregator/src/app/BundleTable.ts]: debug log left here

File: aggregator/src/app/BundleRouter.ts (hunk 18 above)
Comment (blakecduncan) [reply aggregator/src/app/BundleRouter.ts]: Ahh my response was poorly worded.  We are on the same page.  When I said keep the 200 status, I really meant get rid of my logic to add the 202.  You worded it better than I did - that is what I meant to say.

Comment (jacque006) [reply aggregator/src/app/BundleRouter.ts]: Yep, we can discuss offline. In general, I have seen services go one of two ways:

- Use a variety/specific HTTP codes to communicate the state of a resource (200/201/202/403/404/418)
- Use a limited number of status codes (200/403/404) and use a `status` field or similar to communicate the state of the resource (pending/failed/succeeded). Some Google Cloud APIs go this route

I think either is fine as long as we are consistent with that pattern on our endpoints and document the possible responses in code. Hopefully most consumers use our clients which can abstract a lot of that away.

**Review by jacque006 — APPROVED** [review]
:+1: from me. :shipit: once @voltrevo is satisfied

**Review by voltrevo — APPROVED** [review]
