### PR TITLE
Fix fees on optimism

### LINKED ISSUE #602: Fix estimateFee on optimism
We currently use gasEstimate * gasPrice to estimate fees.

On Optimism, the L1 fee is charged separately, so we need to do this calculation separately and add it.
https://community.optimism.io/docs/developers/build/transaction-fees/#displaying-fees-to-users

The L1 fee is also dominant, causing the aggregator to dramatically under-charge the wallets, e.g.:
https://goerli-optimism.etherscan.io/tx/0x0dded0c7c0fafd8a114e5c1d427d259a61a65af487fe17263b4752494b8b340b
`Wallet Fee:     0.000000000060302196`
`Aggregator Fee: 0.035376145885029056`

With the `BREAKEVEN_OPERATION_COUNT=4.5`, it's expected the wallet fee would be lower, but it should still be within an order of magnitude.

### PR DESCRIPTION
**Pull request by voltrevo**
## What is this PR doing?

Fixes #602 using the optimism gas oracle and doing their custom L1 fee calculation.

## How can these changes be manually tested?

Set `BREAKEVEN_OPERATION_COUNT=2.5` and `IS_OPTIMISM=true` on optimism goerli. Run `./manualTests/mintNViaAggregator.ts 3` and verify that the aggregator makes a small profit.

## Does this PR resolve or contribute to any issues?

Resolves #602.

## Checklist
- [x] I have manually tested these changes
- [x] Post a link to the PR in the group chat

## Guidelines
- If your PR is not ready, mark it as a draft
- The `resolve conversation` button is for reviewers, not authors
  - (But add a 'done' comment or similar)

### CODE REVIEW

File: aggregator/src/app/OptimismGasPriceOracle.ts [hunk 1]
```diff
@@ -0,0 +1,53 @@
+import { BigNumber, ethers } from "../../deps.ts";
+import assert from "../helpers/assert.ts";
+
+export default class OptimismGasPriceOracle {
+  static address = "0x420000000000000000000000000000000000000F";
```
Comment (jacque006) [inline aggregator/src/app/OptimismGasPriceOracle.ts]: @jacque006 Move to env file

**Review by jacque006 — COMMENTED** [review]
One minor change I will make, otherwise looks good

File: aggregator/.env.example [hunk 2]
```diff
@@ -40,3 +40,7 @@ PRIORITY_FEE_PER_GAS=0
 PREVIOUS_BASE_FEE_PERCENT_INCREASE=2
 
 BUNDLE_CHECKING_CONCURRENCY=8
+
+IS_OPTIMISM=false
+OPTIMISM_GAS_PRICE_ORACLE_ADDRESS=0x420000000000000000000000000000000000000F
+OPTIMISM_L1_BASE_FEE_PERCENT_INCREASE=2
```
Comment (jacque006) [inline aggregator/.env.example:46]: @voltrevo I used this default value based on `PREVIOUS_BASE_FEE_PERCENT_INCREASE` per docstring, let me know if we should use something else.

File: aggregator/src/app/OptimismGasPriceOracle.ts (hunk 1 above)
Comment (jacque006) [reply aggregator/src/app/OptimismGasPriceOracle.ts]: Done

**Review by jacque006 — APPROVED** [review]
